---
- name: Clone a VM from an existing template or VM in vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Clone VM from template or existing VM
      community.vmware.vmware_guest:
#        hostname: "{{ vcenter_hostname }}"
#        username: "{{ vcenter_username }}"
#        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ vcenter_datacenter }}"
        folder: "{{ vm_folder }}"                     # Folder where the new VM will be placed
        name: "{{ new_vm_name }}"                     # Name of the new VM to be created
        state: poweredon                              # VM state after creation (powered on or powered off)
        template_src: "{{ source_vm_name }}"          # Source VM or template to clone from
        hardware:
          memory_mb: "{{ vm_memory_mb }}"             # Define memory for the new VM (optional)
          num_cpus: "{{ vm_num_cpus }}"               # Define the number of CPUs (optional)
        networks:
          - name: "{{ vm_network }}"                  # Define network to attach to
            ip: "{{ vm_ip }}"                         # Static IP (optional)
            netmask: "{{ vm_netmask }}"               # Netmask (optional)
            gateway: "{{ vm_gateway }}"               # Gateway (optional)
        disk:
          - size_gb: "{{ vm_disk_size }}"             # Define disk size for the new VM (optional)
            datastore: "{{ vm_datastore }}"           # Define the datastore for the new VM
      delegate_to: localhost
