---
- name: Clone a Nutanix VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: List VMs using length, offset, sort order, and vm_name sort attribute
      nutanix.nutanix.nutanix_vm_facts:
        cluster: "{{ nutanix_cluster }}"
        username: "{{ nutanix_username }}"
        password: "{{ nutanix_password }}"
        validate_certs: no
        length: 1
        offset: 1
        sort_order: "ASCENDING"
        sort_attribute: "{{ source_vm_name }}"
      register: result

    - name: Debug VM information
      debug:
        msg: "{{ result }}"
